services:
  - type: web
    name: yolo-streamlit-skin-detector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.enableCORS false --server.enableXsrfProtection false --server.port 10000 --server.address 0.0.0.0
    plan: free